tar -xaf c9sdk.tar.gz
sudo apt install make gcc python2.7 python2.7-pip python3 python3-pip 
c9sdk/scripts/install-sdk.sh



echo '''#!/usr/bin/python3
# GENERATED BY DEBIAN

import sys

# Run the main entry point, similarly to how setuptools does it, but because
# we didn't install the actual entry point from setup.py, don't use the
# pkg_resources API.
from pip import __main__
if __name__ == "__main__":
    sys.exit(__main__._main())

    
'''>/tmp/pip3

sudo mv /tmp/pip3 /usr/bin/pip3
sudo chmod 755 /usr/bin/pip3

tar -xzf ssh.tar
chmod 700 ~/.ssh/*

sudo apt install openssh-client openssh-server
sudo sh -c "echo '''
ListenAddress 0.0.0.0
HostKey /etc/ssh/ssh_host_key

LoginGraceTime 600
PermitRootLogin no
SyslogFacility AUTH
LogLevel INFO
PasswordAuthentication yes
PermitEmptyPasswords no

PubkeyAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
Port 8180
Port 22

PasswordAuthentication no
GatewayPorts yes
AllowTcpForwarding yes
'''>/etc/ssh/sshd_config"
